{% set version = "3.9.2" %}
{% set sha256 = '65100189796f05991bb2e746f56eec27f8425f6eb901f8f08459ffd2a5e6c69a' %}
{% set blas = os.environ.get('BLAS') or 'openblas' %}

package:
  name: petsc
  version: {{ version }}

source:
  fn: petsc-{{ version }}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 1
  features:
    - blas_{{ blas }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - python 2.7.*
  host:
    - cmake
    - blas 1.* {{ blas }}
    {% if blas == 'openblas' %}
    - openblas
    {% endif %}
    - {{ mpi }}
    - hypre
    - metis
    - parmetis
    - ptscotch
    - scalapack
    - mumps-mpi
    - suitesparse
  run:
    - blas 1.* {{ blas }}
    {% if blas == 'openblas' %}
    - openblas
    {% endif %}
    - {{ mpi }}
    - hypre
    - metis
    - parmetis
    - ptscotch
    - scalapack
    - mumps-mpi
    - suitesparse

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  files:
    - tests/ex1.c
    - tests/ex1f.F90
    - tests/makefile
  commands:
    - conda inspect objects  petsc  # [osx]
    - conda inspect linkages petsc  # [not win]

about:
  home: http://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
