{% set version = "3.10.4" %}
{% set sha256 = "1921b2208801d6e03b44035d65d6c11901dbfa6c13a5a0f23864c04f4832613a" %}

package:
  name: petsc
  version: {{ version }}

source:
  fn: petsc-{{ version }}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ignore-not-invalid.patch

build:
  skip: true  # [win]
  number: 0
  # we didn't need to add this feature,
  # but we cannot remove it until blas mpkg drops track_features
  features:
    - blas_openblas
  run_exports:
    - {{ pin_subpackage('petsc', max_pin='x.x')}}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - pkg-config
    - python 2.7.*
  host:
    - cmake
    - openblas
    - {{ mpi }}
    - hypre
    - metis
    - parmetis
    - ptscotch
    - scalapack
    - scotch
    - mumps-mpi
    - suitesparse
  run:
    - openblas
    - {{ mpi }}
    - hypre
    - metis
    - parmetis
    - ptscotch
    - scalapack
    - scotch
    - mumps-mpi
    - suitesparse

test:
  requires:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  files:
    - tests/ex1.c
    - tests/ex1f.F90
    - tests/makefile
  commands:
    - pkg-config --validate PETSc
    - pkg-config --cflags PETSc
    - pkg-config --libs PETSc

about:
  home: http://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
