travis:
  secure:
    BINSTAR_TOKEN: mwSd0ACy1lUXMj+HptfkIp26dEbnB1SegT/1tJLosHZYhWM0ggcIc+4CA+OIIzJluRUmrHnzoTLbdWP4ClpIJiOvXJqv7vB33slQxXGayRyfq5rp8+RpmltJowSK9TAOXF19Xyh7zM0n6/OxiHmPC3dhxGrTWHLt/SmON6Wm0fNaz0iHtpq5STe1fmpouC0mFhP2t/1umR6Qi1MQfNAHKCf9arT/50wx+fNRuxgowJfs1a2duZggvsFCfYmBvpQUmjgmvjKvSeKikm+Q161n7KS/T4J2uGJAlbv+9DSLm/Dh6yqcm21ex3t2BFS0tZjNruNz7WeIvDr2rSICkwzkG+FQH53J69rm4c8Zl+IzFCrymEm+pg62/jIgO/645fLSQtolG59i23jo40BRE/StTMSuzRtznIIwHcqHkhRxGApmqVpiOcgJnrOYFfEptvdyNUdzfYNlU4/cpj6GIfCcKp5mma9xFaOtabhtJxZbxvyUysPuhkzbbXHpEW0dpC2WQjxfSbBK9xNHuXarCbehABMU0qj1i5qsjWglZPEGsKhEokrPUhALL3sBQjLZjAVl9FfkrF22OI3ynRY1WmkfxUmn4q5LF0fQCnxhiWTJvo/S2V3XBlmws22UR7Jxtw19ymjtW/sO+closSoa+xWxbfX0LMdIph0ggIzDp18CYWY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
